"use strict";
const APP_VERSION="6.0.0",STATE_VERSION=60,LS_STATE="fittrack_state_v2",LS_SESSION="fittrack_session_v2",LS_TIMER="fittrack_timer_v2";
const MODE_INFO={normal:"Tam program. Ana hareketlerde 1–3 RIR, yardımcı hareketlerde 1–2 RIR hedefle.",short:"Ana hareketler korunur, yardımcı setler azalır. Hedef 30–40 dakika.",low:"Zinciri koparmama günü. Ağırlığı yaklaşık %5 azalt, 3–4 RIR bırak."};
const $=id=>document.getElementById(id),uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8),num=(v,f=0)=>Number.isFinite(parseFloat(v))?parseFloat(v):f,int=(v,f=0)=>Number.isFinite(parseInt(v,10))?parseInt(v,10):f,clamp=(v,a,b)=>Math.min(b,Math.max(a,v)),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),safe=v=>{try{return JSON.parse(v)}catch{return null}},iso=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`,trDate=(d=new Date())=>d.toLocaleDateString("tr-TR"),trTime=(d=new Date())=>d.toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"}),fmt=s=>`${Math.floor(Math.max(0,s)/60)}:${String(Math.max(0,s)%60).padStart(2,"0")}`;
const storage=(()=>{try{localStorage.setItem("__t","1");localStorage.removeItem("__t");return localStorage}catch{const m={};return{getItem:k=>m[k]??null,setItem:(k,v)=>m[k]=String(v),removeItem:k=>delete m[k]}}})();
let state,session,currentTab="workout",exerciseModalCtx={},confirmAction=null,pendingWorker=null,timer={workoutRunning:false,workoutBase:0,workoutStartedAt:null,restRunning:false,restEndsAt:null,restTarget:90},tick=null;
function toast(m){const e=$("toast");e.textContent=m;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2200)}
function openConfirm(t,m,fn,d=false){$("confirmTitle").textContent=t;$("confirmMessage").textContent=m;const b=$("confirmButton");b.className=`btn ${d?"danger":"primary"}`;b.textContent=d?"Sil":"Devam";confirmAction=fn;$("confirmModal").classList.add("open")}
function closeConfirm(){$("confirmModal").classList.remove("open");confirmAction=null}
$("confirmButton").onclick=()=>{const f=confirmAction;closeConfirm();if(f)f()};
function ex(id,name,muscles,sets,repMin,repMax,weight,type,increment,restSec,optional,note,video,priority="normal"){return{id,name,muscles,sets,repMin,repMax,reps:repMax,weight,type,increment,restSec,optional,note,video,priority}}
function targetProgram(){const A=[
 ex("v2_chest_press","Chest Press (Makine)",["Göğüs","Triceps"],3,8,10,10,"main",2.5,120,false,"Önce boş makine ve hafif ısınma seti yap.","https://www.youtube.com/results?search_query=machine+chest+press+proper+form","high"),
 ex("v2_supported_row","Chest Supported Row / Seated Cable Row",["Orta Sırt","Biceps"],4,8,12,35,"main",2.5,120,false,"Destekli row yoksa kablo row. Gövdeyi savurma.","https://www.youtube.com/results?search_query=chest+supported+row+proper+form","high"),
 ex("v2_leg_press","Leg Press",["Quadriceps","Kalça"],3,10,15,120,"main",5,120,false,"Bel pedden kalkmasın, dizleri kilitleme.","https://www.youtube.com/results?search_query=leg+press+proper+form"),
 ex("v2_lateral_raise","Dumbbell Lateral Raise",["Yan Omuz"],4,12,20,7.5,"accessory",1,60,false,"Savurmadan omuz hizasına kadar kaldır.","https://www.youtube.com/results?search_query=dumbbell+lateral+raise+proper+form","high"),
 ex("v2_db_curl","Dumbbell Biceps Curl",["Biceps"],3,10,15,7.5,"accessory",1,75,true,"Dirsek sabit, gövdeyi sallama.","https://www.youtube.com/results?search_query=dumbbell+biceps+curl+proper+form"),
 ex("v2_pushdown","Rope Triceps Pushdown",["Triceps"],3,10,15,20,"accessory",2.5,75,true,"Dirsekleri gövde yanında sabit tut.","https://www.youtube.com/results?search_query=rope+triceps+pushdown+proper+form"),
 ex("v2_plank","Plank",["Core"],3,30,45,0,"core",0,60,true,"Süreyi tekrar alanına saniye olarak gir.","https://www.youtube.com/results?search_query=plank+proper+form","support")];
 const B=[
 ex("v2_incline_press","Incline Dumbbell Press",["Üst Göğüs","Triceps"],3,8,10,16,"main",1,120,false,"Sehpayı düşük-orta eğimde tut, omuzları geriye sabitle.","https://www.youtube.com/results?search_query=incline+dumbbell+press+proper+form","high"),
 ex("v2_neutral_pulldown","Neutral Grip Lat Pulldown",["Sırt","Biceps"],3,8,12,40,"main",2.5,120,false,"Aşırı geniş tutuş değil; göğse kontrollü çek.","https://www.youtube.com/results?search_query=neutral+grip+lat+pulldown+proper+form"),
 ex("v2_leg_curl","Leg Curl",["Hamstring"],3,10,15,40,"accessory",2.5,90,false,"Kalçayı pedden kaldırmadan kontrollü çalış.","https://www.youtube.com/results?search_query=seated+leg+curl+proper+form"),
 ex("v2_shoulder_press","Seated Dumbbell Shoulder Press",["Omuz","Triceps"],3,8,10,10,"main",1,120,false,"Ağrı oluşturmayan tutuşu kullan, belini aşırı kavislendirme.","https://www.youtube.com/results?search_query=seated+dumbbell+shoulder+press+proper+form","high"),
 ex("v2_face_pull","Face Pull / Reverse Pec Deck",["Arka Omuz","Orta Sırt"],3,12,20,15,"accessory",2.5,75,true,"Reverse pec deck varsa onu da kullanabilirsin.","https://www.youtube.com/results?search_query=face+pull+proper+form","support"),
 ex("v2_shrug","Dumbbell Shrug",["Trapez","Ön Kol"],3,10,15,15,"accessory",2.5,90,true,"Omuzları yukarı kaldır; geriye çevirmeden indir.","https://www.youtube.com/results?search_query=dumbbell+shrug+proper+form","high"),
 ex("v2_hammer","Hammer Curl",["Biceps","Ön Kol"],3,10,15,10,"accessory",1,75,true,"Nötr tutuş, kontrollü negatif.","https://www.youtube.com/results?search_query=hammer+curl+proper+form")];
 const exercises={};[...A,...B].forEach(x=>exercises[x.id]=x);return{workouts:[{id:"v2_a",name:"A · Güç & Kalınlık",focus:"Göğüs, orta sırt, yan omuz ve sağlam alt vücut",exerciseIds:A.map(x=>x.id)},{id:"v2_b",name:"B · Heybet & Arka Zincir",focus:"Üst göğüs, omuz, trapez, hamstring ve sırt gücü",exerciseIds:B.map(x=>x.id)}],exercises}}
function seed(){const p=targetProgram();return{version:STATE_VERSION,appVersion:APP_VERSION,workouts:p.workouts,exercises:p.exercises,logs:[],cardioLog:[],bodyWeightLog:[],settings:{activeWorkoutId:"v2_a",bodyWeightKg:121.5,restSeconds:90,weeklyWorkoutTarget:4,weeklyCardioTarget:120,defaultMode:"normal",vibration:true,wakeLock:true,autoRest:true}}}
function normalizeExercise(x,i=0){x.id=x.id||uid();x.name=x.name||"Hareket";x.muscles=Array.isArray(x.muscles)?x.muscles:[];x.type=x.type||(/plank|core/i.test(x.name)?"core":/curl|raise|pushdown|extension|face pull|shrug|leg curl/i.test(x.name)?"accessory":"main");x.sets=clamp(int(x.sets,3),1,10);x.repMin=int(x.repMin,x.type==="main"?8:10);x.repMax=int(x.repMax,x.type==="main"?10:15);x.weight=num(x.weight);x.increment=num(x.increment,x.weight<=20?1:2.5);x.restSec=int(x.restSec,x.type==="main"?120:75);x.optional=typeof x.optional==="boolean"?x.optional:i>3;x.note=x.note||"";x.video=x.video||"";x.priority=x.priority||"normal";return x}
function migrate(s){if(!s||!Array.isArray(s.workouts)||!s.exercises)return seed();s.logs=Array.isArray(s.logs)?s.logs:[];s.cardioLog=Array.isArray(s.cardioLog)?s.cardioLog:[];s.bodyWeightLog=Array.isArray(s.bodyWeightLog)?s.bodyWeightLog:[];s.settings=s.settings||{};Object.values(s.exercises).forEach(normalizeExercise);s.workouts=s.workouts.map((w,i)=>({id:w.id||uid(),name:w.name||`Antrenman ${i+1}`,focus:w.focus||"",exerciseIds:(w.exerciseIds||[]).filter(id=>s.exercises[id])}));if(!s.workouts.length)return seed();if(!s.workouts.some(w=>w.id===s.settings.activeWorkoutId))s.settings.activeWorkoutId=s.workouts[0].id;s.settings={activeWorkoutId:s.settings.activeWorkoutId,bodyWeightKg:num(s.settings.bodyWeightKg,121.5),restSeconds:int(s.settings.restSeconds,90),weeklyWorkoutTarget:int(s.settings.weeklyWorkoutTarget,4),weeklyCardioTarget:int(s.settings.weeklyCardioTarget,120),defaultMode:MODE_INFO[s.settings.defaultMode]?s.settings.defaultMode:"normal",vibration:s.settings.vibration!==false,wakeLock:s.settings.wakeLock!==false,autoRest:s.settings.autoRest!==false};s.version=STATE_VERSION;s.appVersion=APP_VERSION;return s}
function loadState(){const raw=storage.getItem(LS_STATE),p=safe(raw);if(p){if(p.version!==STATE_VERSION)storage.setItem(`${LS_STATE}_yedek_${Date.now()}`,raw);state=migrate(p)}else state=seed();saveState()}
function saveState(){storage.setItem(LS_STATE,JSON.stringify(state))}
function activeWorkout(){return state.workouts.find(w=>w.id===state.settings.activeWorkoutId)||state.workouts[0]}
function workoutExercises(w=activeWorkout()){return(w.exerciseIds||[]).map(id=>state.exercises[id]).filter(Boolean)}
function nextWorkout(){const i=state.workouts.findIndex(w=>w.id===activeWorkout().id);return state.workouts[(i+1)%state.workouts.length]}
function resetSession(){session={workoutId:activeWorkout().id,mode:state.settings.defaultMode,data:{},createdAt:Date.now()};saveSession();resetTimer()}
function loadSession(){const p=safe(storage.getItem(LS_SESSION));if(p&&p.workoutId===activeWorkout().id){session=p;session.mode=MODE_INFO[p.mode]?p.mode:"normal";session.data=session.data||{}}else resetSession()}
function saveSession(){storage.setItem(LS_SESSION,JSON.stringify(session))}
function entry(ex){return session.data[ex.id]||(session.data[ex.id]={sets:[],note:"",skipped:false})}
function normalizeLog(e,x={}){if(Array.isArray(e.sets))return{...e,sets:e.sets.map(s=>({done:s.done!==false,weight:num(s.weight,num(e.weight,x.weight||0)),reps:int(s.reps,int(e.reps,x.repMin||0)),rir:s.rir==null?null:num(s.rir)}))};return{...e,sets:(e.setsDone||[]).map(v=>({done:!!v,weight:num(e.weight,x.weight||0),reps:int(e.reps,x.repMin||0),rir:null}))}}
function latest(id,skip=0){let n=0;for(let i=state.logs.length-1;i>=0;i--){const e=state.logs[i].entries?.[id];if(e){if(n===skip)return normalizeLog(e,state.exercises[id]);n++}}return null}
function progression(ex){const l=latest(ex.id);if(!l)return{weight:ex.weight,status:"Başlangıç",text:`${ex.repMin}–${ex.repMax} aralığında temiz tekrar ve 1–3 RIR.`};const sets=l.sets.filter(s=>s.done);if(!sets.length)return{weight:ex.weight,status:"Başlangıç",text:"Son kayıtta tamamlanmış set yok."};const w=num(sets[0].weight,ex.weight),allTop=sets.length>=Math.min(ex.sets,2)&&sets.every(s=>s.reps>=ex.repMax),rirs=sets.map(s=>s.rir).filter(v=>v!=null),avg=rirs.length?rirs.reduce((a,b)=>a+b,0)/rirs.length:null,low=sets.filter(s=>s.reps<ex.repMin).length>=Math.ceil(sets.length/2);let weight=w,status="Koru",text=`${w} kg ile tekrarları doldur.`;if(allTop&&(avg==null||avg>=1)){weight=Math.round((w+ex.increment)/ex.increment)*ex.increment;status="Artır";text=`Tüm setler üst sınıra ulaştı. ${weight} kg dene.`}else if(low||avg===0)text=`Ağırlığı artırma; ${w} kg ile temiz formu koru.`;if(session.mode==="low"&&weight>0){weight=Math.max(0,weight-ex.increment);status="Bugün hafif";text=`${weight} kg ve 3–4 RIR yeterli.`}return{weight,status,text}}
function defaultSet(ex,i){const l=latest(ex.id),p=progression(ex);return{done:false,weight:p.weight,reps:l?.sets?.[i]?.reps||ex.repMin,rir:session.mode==="low"?3:2}}
function getSet(ex,i){const e=entry(ex);return e.sets[i]||(e.sets[i]=defaultSet(ex,i))}
function plannedExercises(){const all=workoutExercises();return session.mode==="normal"?all:session.mode==="short"?all.filter((x,i)=>!x.optional||i<4).slice(0,6):all.filter((x,i)=>!x.optional||i<3).slice(0,4)}
function plannedSets(ex){return session.mode==="normal"?ex.sets:Math.min(ex.sets,ex.type==="main"?2:1)}
function currentExercise(){for(const ex of plannedExercises()){const e=entry(ex);if(e.skipped)continue;for(let i=0;i<plannedSets(ex);i++)if(!getSet(ex,i).done)return{ex,index:i}}return null}
function counts(){let done=0,total=0;plannedExercises().forEach(ex=>{const e=entry(ex);if(e.skipped)return;total+=plannedSets(ex);for(let i=0;i<plannedSets(ex);i++)if(getSet(ex,i).done)done++});return{done,total}}
function totals(){let sets=0,volume=0,reps=0;plannedExercises().forEach(ex=>{const e=entry(ex);if(e.skipped)return;for(let i=0;i<plannedSets(ex);i++){const s=getSet(ex,i);if(s.done){sets++;reps+=s.reps;if(ex.type!=="core")volume+=num(s.weight)*int(s.reps)}}});return{sets,volume,reps}}
function setMode(m){session.mode=m;saveSession();renderWorkout()}
function updateSet(id,i,f,v){const ex=state.exercises[id],s=getSet(ex,i);s[f]=num(v,s[f]);saveSession();renderLive()}
function nudge(id,i,f,d){const ex=state.exercises[id],s=getSet(ex,i),step=f==="weight"?(ex.increment||1):1;s[f]=Math.max(0,num(s[f])+d*step);saveSession();renderWorkout()}
function toggleSet(id,i){const ex=state.exercises[id],s=getSet(ex,i);s.done=!s.done;if(s.done){startWorkout();if(state.settings.autoRest)startRest(ex.restSec);if(state.settings.vibration&&navigator.vibrate)navigator.vibrate(30)}saveSession();renderWorkout()}
function skipExercise(id){const ex=state.exercises[id],e=entry(ex);e.skipped=!e.skipped;saveSession();renderWorkout()}
function updateNote(id,v){entry(state.exercises[id]).note=v;saveSession()}
function completeNextSet(){const c=currentExercise();if(!c)return finishWorkout();getSet(c.ex,c.index).done=true;startWorkout();if(state.settings.autoRest)startRest(c.ex.restSec);saveSession();renderWorkout();setTimeout(scrollCurrent,50)}
function scrollCurrent(){const c=currentExercise();if(c)$(`ex-${c.ex.id}`)?.scrollIntoView({behavior:"smooth",block:"center"})}
function renderWorkout(){document.querySelectorAll(".mode-btn").forEach(b=>b.classList.toggle("on",b.dataset.mode===session.mode));$("modeNote").textContent=MODE_INFO[session.mode];const w=activeWorkout(),c=counts(),cur=currentExercise(),pct=c.total?Math.round(c.done/c.total*100):0;$("hero").innerHTML=`<div class="hero"><div class="hero-top"><div><div class="eyebrow">${cur?`Sıradaki · Set ${cur.index+1}`:"Bugünün programı"}</div><div class="hero-name">${cur?esc(cur.ex.name):"Tamamlandı 🎯"}</div><div class="hero-focus">${cur?esc(progression(cur.ex).text):esc(w.focus)}</div></div><div class="ring" style="--progress:${pct}%"><span>${pct}%</span></div></div><div class="hero-actions"><button class="btn primary" onclick="completeNextSet()">${cur?"Sıradaki seti tamamla":"Antrenmanı kaydet"}</button><button class="btn ghost" onclick="scrollCurrent()">Odaklan</button></div><div class="progress"><i style="width:${pct}%"></i></div></div>`;$("exerciseList").innerHTML=plannedExercises().map((x,i)=>exerciseHTML(x,i,cur?.ex.id)).join("");renderLive();renderSelect()}
function exerciseHTML(ex,index,currentId){const e=entry(ex),n=plannedSets(ex),done=e.skipped?0:Array.from({length:n},(_,i)=>getSet(ex,i)).filter(s=>s.done).length,complete=done===n&&!e.skipped,p=progression(ex),l=latest(ex.id);let rows="";for(let i=0;i<n;i++){const s=getSet(ex,i),core=ex.type==="core";rows+=`<div class="set-row ${s.done?"done":""}"><div class="set-index">${i+1}</div><div class="stepper">${core?`<button disabled>−</button><input value="Vücut" disabled><button disabled>+</button>`:`<button onclick="nudge('${ex.id}',${i},'weight',-1)">−</button><input type="number" value="${s.weight}" onchange="updateSet('${ex.id}',${i},'weight',this.value)"><button onclick="nudge('${ex.id}',${i},'weight',1)">+</button>`}</div><div class="stepper"><button onclick="nudge('${ex.id}',${i},'reps',-1)">−</button><input type="number" value="${s.reps}" onchange="updateSet('${ex.id}',${i},'reps',this.value)"><button onclick="nudge('${ex.id}',${i},'reps',1)">+</button></div><select class="rir" onchange="updateSet('${ex.id}',${i},'rir',this.value)">${[0,1,2,3,4].map(v=>`<option ${s.rir==v?"selected":""}>${v}</option>`).join("")}</select><button class="done-btn ${s.done?"on":""}" onclick="toggleSet('${ex.id}',${i})">${s.done?"✓":"○"}</button></div>`}const lastText=l?l.sets.filter(s=>s.done).map(s=>`${s.weight||"Vücut"}${s.weight?" kg":""}×${s.reps}`).join(" · "):"Kayıt yok";return`<section class="exercise ${currentId===ex.id?"current":""} ${complete?"complete":""} ${e.skipped?"skipped":""}" id="ex-${ex.id}"><div class="ex-head"><div class="ex-no">${complete?"✓":index+1}</div><div class="ex-main"><div class="ex-name">${esc(ex.name)}</div><div class="ex-note">${esc(ex.note)}</div><div class="tags">${ex.muscles.map(m=>`<span class="tag accent">${esc(m)}</span>`).join("")}<span class="tag blue">${n}×${ex.repMin}–${ex.repMax}</span><span class="tag">${ex.restSec} sn</span>${ex.priority==="high"?`<span class="tag orange">Öncelik</span>`:""}</div></div><div class="ex-score"><strong>${done}/${n}</strong><span>set</span></div></div><div class="coach"><b>${p.status}:</b> ${esc(p.text)}<span class="last-line">Son: ${esc(lastText)}</span></div><div class="set-head"><span>Set</span><span>Kg</span><span>${ex.type==="core"?"Sn":"Tekrar"}</span><span>RIR</span><span></span></div>${rows}<div class="ex-actions"><div><a class="link-btn" target="_blank" href="${esc(ex.video)}">▶ Form</a><button class="link-btn muted" onclick="openExerciseModal('${activeWorkout().id}','${ex.id}')">Düzenle</button></div><button class="link-btn muted" onclick="skipExercise('${ex.id}')">${e.skipped?"Geri al":"Bugün atla"}</button></div><div class="session-note"><input class="input" value="${esc(e.note)}" placeholder="Seans notu..." onchange="updateNote('${ex.id}',this.value)"></div></section>`}
function renderLive(){const t=totals();$("liveMetrics").innerHTML=`<div class="metric"><div class="metric-value">${t.sets}</div><div class="metric-label">Set</div></div><div class="metric"><div class="metric-value">${Math.round(t.volume)}</div><div class="metric-label">Hacim kg</div></div><div class="metric"><div class="metric-value">${t.reps}</div><div class="metric-label">Tekrar/sn</div></div><div class="metric"><div class="metric-value">${nextWorkout()?.name.startsWith("B")?"B":"A"}</div><div class="metric-label">Sıradaki</div></div>`}
function elapsed(){return timer.workoutBase+(timer.workoutRunning?Math.floor((Date.now()-timer.workoutStartedAt)/1000):0)}
function saveTimer(){storage.setItem(LS_TIMER,JSON.stringify(timer))}
function resetTimer(){timer={workoutRunning:false,workoutBase:0,workoutStartedAt:null,restRunning:false,restEndsAt:null,restTarget:state?.settings?.restSeconds||90};saveTimer();syncTimers()}
function loadTimer(){timer={...timer,...safe(storage.getItem(LS_TIMER))};clearInterval(tick);tick=setInterval(syncTimers,500);syncTimers()}
function startWorkout(){if(!timer.workoutRunning){timer.workoutRunning=true;timer.workoutStartedAt=Date.now();saveTimer()}}
function startRest(sec=90){timer.restTarget=int(sec,90);timer.restRunning=true;timer.restEndsAt=Date.now()+timer.restTarget*1000;saveTimer();syncTimers()}
function toggleRest(){timer.restRunning=!timer.restRunning;if(timer.restRunning)timer.restEndsAt=Date.now()+timer.restTarget*1000;saveTimer();syncTimers()}
function syncTimers(){$("workoutTimer").textContent=fmt(elapsed());let r=timer.restTarget;if(timer.restRunning){r=Math.max(0,Math.ceil((timer.restEndsAt-Date.now())/1000));if(!r){timer.restRunning=false;saveTimer();if(state?.settings?.vibration&&navigator.vibrate)navigator.vibrate([100,80,100])}}$("restTimer").textContent=fmt(r)}
function finishWorkout(){const c=counts();if(!c.done)return toast("Önce en az bir set tamamla.");const w=activeWorkout(),entries={};plannedExercises().forEach(ex=>{const e=entry(ex),sets=e.sets.slice(0,plannedSets(ex));if(!e.skipped&&sets.some(s=>s.done))entries[ex.id]={name:ex.name,sets,note:e.note}});const t=totals(),duration=Math.max(1,Math.round(elapsed()/60));state.logs.push({id:uid(),date:trDate(),dateISO:iso(),ts:Date.now(),workoutId:w.id,workoutName:w.name,mode:session.mode,duration,totalVolume:t.volume,entries});state.settings.activeWorkoutId=nextWorkout()?.id||w.id;saveState();$("summaryBody").innerHTML=`<div style="text-align:center"><div class="modal-title">Antrenman tamamlandı ✓</div><div class="mode-note">${duration} dk · ${t.sets} set · ${Math.round(t.volume)} kg hacim</div><button class="btn primary full" style="margin-top:12px" onclick="closeSummary()">Tamam</button></div>`;$("summaryModal").classList.add("open");resetSession();renderAll()}
function closeSummary(){$("summaryModal").classList.remove("open")}
function parseDate(v,ts){if(ts)return new Date(ts);if(/^\d{4}-\d{2}-\d{2}$/.test(v||"")){const[y,m,d]=v.split("-").map(Number);return new Date(y,m-1,d)}return new Date(0)}
function weekStart(){const d=new Date(),day=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day);return d}
function weekLogs(){const s=weekStart();return state.logs.filter(l=>parseDate(l.dateISO,l.ts)>=s)}
function weekCardio(){const s=weekStart();return state.cardioLog.filter(l=>parseDate(l.dateISO,l.ts)>=s)}
function renderHistory(){const logs=state.logs.slice().reverse();$("historyContent").innerHTML=logs.length?logs.map(l=>`<div class="card log-card"><div class="log-top"><div class="log-title">${esc(l.date)} · ${esc(l.workoutName)}</div><div class="log-meta">${l.duration||"?"} dk<br>${Math.round(l.totalVolume||0)} kg</div></div><div class="log-body">${Object.entries(l.entries||{}).map(([id,e])=>`<div class="log-ex"><b>${esc(e.name||state.exercises[id]?.name)}</b><br>${normalizeLog(e,state.exercises[id]).sets.filter(s=>s.done).map((s,i)=>`${i+1}. set: ${s.weight?s.weight+" kg · ":""}${s.reps} tekrar · RIR ${s.rir??"—"}`).join("<br>")}</div>`).join("")}</div><button class="btn danger" onclick="deleteLog('${l.id}')">Kaydı sil</button></div>`).join(""):`<div class="empty">Henüz antrenman kaydı yok.</div>`}
function deleteLog(id){openConfirm("Kaydı sil","Bu işlem geri alınamaz.",()=>{state.logs=state.logs.filter(l=>l.id!==id);saveState();renderHistory()},true)}
function muscleGroup(ex){const t=[ex?.name,...(ex?.muscles||[])].join(" ").toLowerCase();if(/göğüs|chest|incline/.test(t))return"Göğüs";if(/row|pulldown|sırt|lat/.test(t))return"Sırt";if(/omuz|shoulder|lateral|face pull/.test(t))return"Omuz";if(/trapez|shrug/.test(t))return"Trapez";if(/biceps|triceps|curl|pushdown/.test(t))return"Kol";if(/leg|bacak|hamstring|quadriceps|kalça/.test(t))return"Bacak";return"Core"}
function renderAnalysis(){const wl=weekLogs(),wc=weekCardio(),mins=wc.reduce((a,c)=>a+num(c.duration),0),sets=wl.reduce((a,l)=>a+Object.values(l.entries||{}).reduce((b,e)=>b+normalizeLog(e).sets.filter(s=>s.done).length,0),0),mus={Göğüs:0,Sırt:0,Omuz:0,Trapez:0,Kol:0,Bacak:0,Core:0};wl.forEach(l=>Object.entries(l.entries||{}).forEach(([id,e])=>mus[muscleGroup(state.exercises[id])]+=normalizeLog(e).sets.filter(s=>s.done).length));const mx=Math.max(1,...Object.values(mus));$("analysisContent").innerHTML=`<div class="summary-grid"><div class="summary-card"><strong>${wl.length}/${state.settings.weeklyWorkoutTarget}</strong><span>Antrenman</span></div><div class="summary-card"><strong>${sets}</strong><span>Çalışma seti</span></div><div class="summary-card"><strong>${mins}</strong><span>Kardiyo dk</span></div><div class="summary-card"><strong>${state.logs.length}</strong><span>Toplam kayıt</span></div></div><div class="section-title">Bu haftanın set dağılımı</div><div class="panel">${Object.entries(mus).map(([k,v])=>`<div class="muscle-row"><div class="muscle-name">${k}</div><div class="muscle-bar"><i style="width:${v/mx*100}%"></i></div><div class="muscle-count">${v}</div></div>`).join("")}</div><div class="section-title">Kilo</div><div class="panel"><div class="grid2"><div class="field"><label>Bugünkü kilo</label><input class="input" id="weightInput" type="number" value="${state.settings.bodyWeightKg}"></div><div class="field" style="display:flex;align-items:end"><button class="btn primary full" onclick="addWeight()">Kaydet</button></div></div></div>`}
function addWeight(){const w=num($("weightInput").value);if(w<50||w>300)return toast("Geçerli kilo gir.");state.settings.bodyWeightKg=w;state.bodyWeightLog.push({id:uid(),date:trDate(),dateISO:iso(),ts:Date.now(),weight:w});saveState();toast("Kilo kaydedildi")}
function walkKcal(w,s,i,m){const sm=s*1000/60,vo2=.1*sm+1.8*sm*(i/100)+3.5;return Math.max(0,vo2*w/1000*5*m)}
function renderCardio(){const wk=weekCardio(),mins=wk.reduce((a,c)=>a+num(c.duration),0),kcal=wk.reduce((a,c)=>a+num(c.kcal),0);$("cardioContent").innerHTML=`<div class="summary-grid"><div class="summary-card"><strong>${mins}</strong><span>Haftalık dk</span></div><div class="summary-card"><strong>${Math.round(kcal)}</strong><span>Tahmini kcal</span></div></div><div class="panel"><div class="grid2"><div class="field"><label>Süre</label><input class="input" id="cDuration" value="35"></div><div class="field"><label>Hız</label><input class="input" id="cSpeed" value="4.6"></div><div class="field"><label>Eğim</label><input class="input" id="cIncline" value="5.5"></div><div class="field"><label>Nabız</label><input class="input" id="cHr" placeholder="125"></div></div><button class="btn primary full" onclick="addCardio()">Kardiyoyu Kaydet</button></div>${state.cardioLog.slice().reverse().map(c=>`<div class="card log-card"><div class="log-title">${c.date} · ${c.duration} dk</div><div class="log-body">${c.speed} km/s · %${c.incline} eğim · ${c.kcal} kcal${c.avgHr?" · "+c.avgHr+" nabız":""}</div><button class="btn danger" onclick="deleteCardio('${c.id}')">Sil</button></div>`).join("")}`}
function addCardio(){const duration=num($("cDuration").value),speed=num($("cSpeed").value),incline=num($("cIncline").value),avgHr=int($("cHr").value);if(!duration||!speed)return toast("Süre ve hız gerekli.");const kcal=Math.round(walkKcal(state.settings.bodyWeightKg,speed,incline,duration));state.cardioLog.push({id:uid(),date:trDate(),dateISO:iso(),ts:Date.now(),duration,speed,incline,avgHr,kcal});saveState();renderCardio();toast(`${kcal} kcal tahminiyle kaydedildi`)}
function deleteCardio(id){openConfirm("Kardiyoyu sil","Kayıt silinecek.",()=>{state.cardioLog=state.cardioLog.filter(c=>c.id!==id);saveState();renderCardio()},true)}
function installTargetProgram(){openConfirm("Yeni A/B programını kur","Geçmiş korunur; mevcut programın otomatik yedeği alınır.",()=>{storage.setItem(`${LS_STATE}_program_yedek_${Date.now()}`,JSON.stringify(state));const p=targetProgram();state.workouts=p.workouts;Object.assign(state.exercises,p.exercises);state.settings.activeWorkoutId="v2_a";saveState();resetSession();renderAll();showTab("workout");toast("Yeni program kuruldu")})}
function renderProgram(){$("programContent").innerHTML=`<div class="panel"><div class="program-name">Güçlü ve heybetli fizik programı</div><div class="mode-note">Göğüs, orta sırt, yan omuz, trapez, kol ve sağlam bacak önceliği.</div><button class="btn primary full" style="margin-top:10px" onclick="installTargetProgram()">Yeni A/B Programını Kur</button></div>${state.workouts.map(w=>`<div class="card program-card"><div class="program-head"><div><div class="program-name">${esc(w.name)}</div><div class="program-meta">${w.exerciseIds.length} hareket · ${esc(w.focus)}</div></div><button class="btn ghost" onclick="addExercise('${w.id}')">+ Hareket</button></div>${w.exerciseIds.map((id,i)=>{const x=state.exercises[id];return`<div class="exercise-manage"><div><div class="manage-name">${i+1}. ${esc(x.name)}</div><div class="manage-note">${x.sets}×${x.repMin}–${x.repMax} · ${x.restSec} sn</div></div><div class="icon-actions"><button class="icon-btn" onclick="moveExercise('${w.id}','${id}',-1)">↑</button><button class="icon-btn" onclick="moveExercise('${w.id}','${id}',1)">↓</button><button class="icon-btn" onclick="openExerciseModal('${w.id}','${id}')">✎</button><button class="icon-btn danger" onclick="removeExercise('${w.id}','${id}')">×</button></div></div>`}).join("")}</div>`).join("")}<div class="panel"><div class="grid2"><div class="field"><label>Haftalık ağırlık</label><input class="input" id="sWorkoutTarget" value="${state.settings.weeklyWorkoutTarget}"></div><div class="field"><label>Kardiyo dk</label><input class="input" id="sCardioTarget" value="${state.settings.weeklyCardioTarget}"></div><div class="field"><label>Dinlenme sn</label><input class="input" id="sRest" value="${state.settings.restSeconds}"></div><div class="field"><label>Kilo</label><input class="input" id="sWeight" value="${state.settings.bodyWeightKg}"></div></div><label class="check"><input id="sAutoRest" type="checkbox" ${state.settings.autoRest?"checked":""}> Otomatik dinlenme</label><button class="btn primary full" style="margin-top:10px" onclick="saveSettings()">Ayarları Kaydet</button><div class="button-row" style="margin-top:8px"><button class="btn blue" onclick="exportData()">Yedek İndir</button><button class="btn ghost" onclick="$('importFile').click()">Yedek Yükle</button></div></div>`}
function saveSettings(){state.settings.weeklyWorkoutTarget=int($("sWorkoutTarget").value,4);state.settings.weeklyCardioTarget=int($("sCardioTarget").value,120);state.settings.restSeconds=int($("sRest").value,90);state.settings.bodyWeightKg=num($("sWeight").value,121.5);state.settings.autoRest=$("sAutoRest").checked;saveState();toast("Ayarlar kaydedildi")}
function addExercise(wid){exerciseModalCtx={workoutId:wid,exerciseId:null};["fName","fMuscles","fWeight","fVideo","fNote"].forEach(id=>$(id).value="");$("fSets").value=3;$("fRepMin").value=10;$("fRepMax").value=15;$("fIncrement").value=1;$("fRest").value=75;$("fType").value="accessory";$("fPriority").value="normal";$("fOptional").checked=true;$("exerciseModal").classList.add("open")}
function openExerciseModal(wid,id){const x=state.exercises[id];exerciseModalCtx={workoutId:wid,exerciseId:id};$("fName").value=x.name;$("fMuscles").value=x.muscles.join(", ");$("fWeight").value=x.weight;$("fSets").value=x.sets;$("fRepMin").value=x.repMin;$("fRepMax").value=x.repMax;$("fType").value=x.type;$("fIncrement").value=x.increment;$("fRest").value=x.restSec;$("fPriority").value=x.priority;$("fVideo").value=x.video;$("fNote").value=x.note;$("fOptional").checked=x.optional;$("exerciseModal").classList.add("open")}
function closeExerciseModal(){$("exerciseModal").classList.remove("open")}
function saveExerciseModal(){const name=$("fName").value.trim();if(!name)return toast("Hareket adı gerekli.");const id=exerciseModalCtx.exerciseId||uid(),x=normalizeExercise({id,name,muscles:$("fMuscles").value.split(",").map(x=>x.trim()).filter(Boolean),weight:num($("fWeight").value),sets:int($("fSets").value,3),repMin:int($("fRepMin").value,10),repMax:int($("fRepMax").value,15),type:$("fType").value,increment:num($("fIncrement").value,1),restSec:int($("fRest").value,75),priority:$("fPriority").value,video:$("fVideo").value,note:$("fNote").value,optional:$("fOptional").checked});state.exercises[id]=x;const w=state.workouts.find(w=>w.id===exerciseModalCtx.workoutId);if(!w.exerciseIds.includes(id))w.exerciseIds.push(id);saveState();closeExerciseModal();renderAll()}
function moveExercise(wid,id,d){const w=state.workouts.find(w=>w.id===wid),i=w.exerciseIds.indexOf(id),j=i+d;if(j<0||j>=w.exerciseIds.length)return;[w.exerciseIds[i],w.exerciseIds[j]]=[w.exerciseIds[j],w.exerciseIds[i]];saveState();renderProgram()}
function removeExercise(wid,id){openConfirm("Hareketi çıkar","Geçmiş kayıtlar korunur.",()=>{const w=state.workouts.find(w=>w.id===wid);w.exerciseIds=w.exerciseIds.filter(x=>x!==id);saveState();resetSession();renderAll()},true)}
function exportData(){const blob=new Blob([JSON.stringify({appVersion:APP_VERSION,state},null,2)],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`antrenman-yedek-${iso()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function importData(file){if(!file)return;const r=new FileReader();r.onload=()=>{const p=safe(r.result),s=p?.state||p;if(!s?.workouts)return toast("Geçerli yedek değil.");openConfirm("Yedeği yükle","Mevcut veriler yedeklenecek.",()=>{storage.setItem(`${LS_STATE}_ithalat_${Date.now()}`,JSON.stringify(state));state=migrate(s);saveState();resetSession();renderAll()})};r.readAsText(file)}
function renderSelect(){const s=$("workoutSelect");s.innerHTML=state.workouts.map(w=>`<option value="${w.id}" ${w.id===activeWorkout().id?"selected":""}>${esc(w.name)}</option>`).join("");s.onchange=()=>{state.settings.activeWorkoutId=s.value;saveState();resetSession();renderAll()}}
function showTab(t){currentTab=t;document.querySelectorAll(".page").forEach(p=>p.classList.toggle("on",p.id===`page-${t}`));document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("on",b.dataset.tab===t));if(t==="history")renderHistory();if(t==="analysis")renderAnalysis();if(t==="cardio")renderCardio();if(t==="program")renderProgram();scrollTo(0,0)}
function renderAll(){renderSelect();renderWorkout();$("dateText").textContent=new Date().toLocaleDateString("tr-TR",{weekday:"long",day:"numeric",month:"long"});if(currentTab!=="workout")showTab(currentTab)}
function registerSW(){if(!("serviceWorker" in navigator))return;navigator.serviceWorker.register("./sw.js").then(r=>{if(r.waiting){pendingWorker=r.waiting;$("updateBanner").classList.add("show")}r.addEventListener("updatefound",()=>r.installing?.addEventListener("statechange",()=>{if(r.installing.state==="installed"&&navigator.serviceWorker.controller){pendingWorker=r.installing;$("updateBanner").classList.add("show")}}))}).catch(()=>{});navigator.serviceWorker.addEventListener("controllerchange",()=>location.reload())}
function activateUpdate(){pendingWorker?.postMessage({type:"SKIP_WAITING"})}
loadState();loadSession();loadTimer();renderAll();registerSW();
